<a href="https://colab.research.google.com/github/1Asfandyar/Smart-Attendance-System/blob/flask_api/app.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# install required pakages
!pip install flask
!pip install flask-ngrok

!pip install face_recognition
!pip install -v --install-option="--no" --install-option="DLIB_USE_CUDA" dlib
!pip install mtcnn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 100.1 MB 24 kB/s 
  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566186 sha256=a2b74f0024f31bef5b59961d46ba50792d76209deb1cd2588d5e5aa0f96021b1
  Stored in directory: /root/.cache/pip/wheels/d6/81/3c/884bcd5e1c120ff548d57c2ecc9ebf3281c9a6f7c0e7e7947a
Successfully built face-recognition-models
/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Using pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip

In [2]:
# if you are surving HTML content then you need to run this
# downloading, extracting, and saving configs ngrok
!wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
!tar -xvzf ngrok-v3-stable-linux-amd64.tgz
!./ngrok config add-authtoken 29ifuhUWiH23ARpVC0PyPdnBSrj_4q2eJgbA1qthKRH4LevY
! rm *.tgz*

--2022-05-27 11:01:47--  https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
Resolving bin.equinox.io (bin.equinox.io)... 54.237.133.81, 18.205.222.128, 54.161.241.46, ...
Connecting to bin.equinox.io (bin.equinox.io)|54.237.133.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7166947 (6.8M) [application/octet-stream]
Saving to: ‘ngrok-v3-stable-linux-amd64.tgz’

ngrok-v3-stable-lin 100%[===================>]   6.83M  12.1MB/s    in 0.6s    

2022-05-27 11:01:48 (12.1 MB/s) - ‘ngrok-v3-stable-linux-amd64.tgz’ saved [7166947/7166947]

ngrok
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml


In [3]:
import os
from flask import Flask, jsonify, request

from flask import Flask
from flask_ngrok import run_with_ngrok

In [4]:
# please first uploade all file from helper folder
# and updated_ml_function.py from ML_model foler

In [8]:
from log import debug, info, warning, error
from req_handler import present_students
from decode_img import decode
from encode_img import encode
from updated_ml_function import takeAttendence

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
!cat decode_img.py

import numpy as np
from PIL import Image
import io
import base64

def decode(str_img:str):
    # this method take base64 incoded image and returns the data
    # which is required for decoding the image.
    return np.array(Image.open(io.BytesIO(base64.b64decode(str_img))))

In [29]:
import numpy as np
from PIL import Image
import io
import base64

In [10]:
app = Flask(__name__)
run_with_ngrok(app)   

@app.route("/")
def home():
  body = request.get_json()
  img = decode(body["class_img"])
  print(img)
  headers = request.headers
  return "Hello World"
  # return jsonify(takeAttendence(Name_list, StudentFaces_Encoding, ClassroomImagePath))

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://6e07-35-247-100-249.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [27/May/2022 11:03:55] "GET / HTTP/1.1" 200 -


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 0 0]
  [0 1 0]
  [0 4 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [1 0 0]
  [0 2 0]
  [0 4 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 2 0]
  [0 5 0]]]
